version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "8081:80"
    volumes:
      - ./files:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
